/* Generated by GoScript <github.com/kless/GoScript> */



function testIf() {
	var x = 5;
	var code = "";


	if (x > 10) {
		code = "Error";
	} else {
		code = "OK";
	}
	console.log("[" + code + "] simple\n");


	var x = 12; if (x > 10) {
		code = "OK";
	} else {
		code = "Error";
	}
	console.log("[" + code + "] with statement\n");


	var i = 7;

	if (i === 3) {
		code = "Error";
	} else if (i < 3) {
		code = "Error";
	} else {
		code = "OK";
	}
	console.log("[" + code + "] multiple\n");
}

function testSwitch() {
	var i = 10;
	var code = "";


	switch (i) {
	default:
		code = "Error"; break;
	case 1:
		code = "Error"; break;
	case 2: case 3: case 4:
		code = "Error"; break;
	case 10:
		code = "OK";
	}
	console.log("[" + code + "] simple\n");


	i = 5; switch (true) {
	case i < 10:
		code = "OK"; break;
	case i > 10: case i < 0:
		code = "Error"; break;
	case i === 10:
		code = "Error"; break;
	default:
		code = "Error";
	}
	console.log("[" + code + "] with statement\n");

	switch (true) {
	case i === 5:
		code = "OK";
	}
	console.log("[" + code + "] without expression\n");


	switch (i) {
	case 4:
		code = "Error";
		
	case 5:
		code = "Error";
		
	case 6:
		code = "Error";
		
	case 7:
		code = "OK"; break;
	case 8:
		code = "Error"; break;
	default:
		code = "Error";
	}
	console.log("[" + code + "] with fallthrough\n");
}

function testFor() {
	var sum = 0;


	for (var i = 0; i < 10; i++) {
		sum += i;
	}

	var code = "";
	if (sum === 45) {
		code = "OK";
	} else {
		code = "Error";
	}
	console.log("[" + code + "] simple\n");



	sum = 1;
	for (; sum < 1000;) {
		sum += sum;
	}

	if (sum === 1024) {
		code = "OK";
	} else {
		code = "Error";
	}
	console.log("[" + code + "] 2 expressions omitted\n");



	sum = 1;
	for (; sum < 1000;) {
		sum += sum;
	}

	if (sum === 1024) {
		code = "OK";
	} else {
		code = "Error";
	}
	console.log("[" + code + "] 2 expressions omitted, no semicolons\n");



	var i = 0;
	var s = "";
	for (;;) {
		i++;
		if (i === 3) {
			s = "" + i + "";
			break;
		}
	}

	if (s === "3") {
		code = "OK";
	} else {
		code = "Error";
	}
	console.log("[" + code + "] infinite loop\n");



	s = "";
	for (var i = 10; i > 0; i--) {
		if (i < 5) {
			break;
		}
		s += "" + i + " ";
	}

	if (s === "10 9 8 7 6 5 ") {
		console.log("[OK] break\n");
	} else {
		alert("[Error] value in break: " + s + "\n");
	}



	s = "";
	for (var i = 10; i > 0; i--) {
		if (i === 5) {
			continue;
		}
		s += "" + i + " ";
	}

	if (s === "10 9 8 7 6 4 3 2 1 ") {
		console.log("[OK] continue\n");
	} else {
		alert("[Error] value in continue: " + s + "\n");
	}

}

function testRange() {
	var s = [2, 3, 5];

	var v; for (i in s) { v = s[i];
		console.log("key: " + i + " " + "value: " + v + "\n");
	}
}

function main() {
	console.log("\n== testIf\n");
	testIf();
	console.log("\n== testSwitch\n");
	testSwitch();
	console.log("\n== testFor\n");
	testFor();


}
