/* Generated by GoScript <github.com/kless/GoScript> */

function testIf() {
	var x = 5;


	if (x > 10) {
		console.log("x = " + x + " " + "is greater than 10\n");
	} else {
		console.log("x = " + x + " " + "is less than 10\n");
	}


	var x = 12; if (x > 10) {
		console.log("x = " + x + " " + "is greater than 10\n");
	} else {
		console.log("x = " + x + " " + "is less than 10\n");
	}


	var i = 7;

	if (i === 3) {
		console.log("i = " + i + " " + "is equal to 3\n");
	} else if (i < 3) {
		console.log("i = " + i + " " + "is less than 3\n");
	} else {
		console.log("i = " + i + " " + "is greater than 3\n");
	}
}

function testSwitch() {
	var i = 10;


	switch (i) {
	case 1:
		console.log("i = " + i + " " + "is equal to 1\n"); break;
	case 2: case 3: case 4:
		console.log("i = " + i + " " + "is equal to 2, 3 or 4\n"); break;
	case 10:
		console.log("i = " + i + " " + "is equal to 10\n"); break;
	default:
		console.log("All I know is that i is an integer\n");
	}


	i = 5; switch (true) {
	case i < 10:
		console.log("i = " + i + " " + "is less than 10\n"); break;
	case i > 10: case i < 0:
		console.log("i = " + i + " " + "is either bigger than 10 or less than 0\n"); break;
	case i === 10:
		console.log("i = " + i + " " + "is equal to 10\n"); break;
	default:
		console.log("This won't be printed anyway\n");
	}

	switch (true) {
	case i === 5:
		console.log("i is 5\n");
	}


	switch (i) {
	case 4:
		console.log("was <= 4\n");
		
	case 5:
		console.log("was <= 5\n");
		
	case 6:
		console.log("was <= 6\n");
		
	case 7:
		console.log("was <= 7\n");
		
	case 8:
		console.log("was <= 8\n"); break;

	default:
		console.log("default case\n");
	}


	switch (i) {
	default: break;
	case 1: case 3: case 5: case 7: case 9:
		return "odd";
	case 2: case 4: case 6: case 8:
		return "even";
	}

	return "";
}

function testFor() {
	var sum = 0;


	for (var i = 0; i < 10; i++) {
		sum += i;
	}
	console.log("sum is equal to " + sum + "\n");


	sum = 1;
	for (; sum < 1000;) {
		sum += sum;
	}
	console.log("sum is equal to " + sum + "\n");


	sum = 1;
	for (; sum < 1000;) {
		sum += sum;
	}
	console.log("sum is equal to " + sum + "\n");


	var i = 0;
	for (;;) {
		console.log("I loop for ever!\n");
		i++;
		if (i === 3) {
			break;
		}
	}


	console.log("break on 5: ");
	for (var i = 10; i > 0; i--) {
		if (i < 5) {
			break;
		}
		console.log(i + " ");
	}


	console.log("\nskip 5: ");
	for (var i = 10; i > 0; i--) {
		if (i === 5) {
			continue;
		}
		console.log(i + " ");
	}
	console.log();
}

function testRange() {
	var s = [2, 3, 5];

	var v; for (i in s) { v = s[i];
		console.log("key: " + i + " " + "value: " + v + "\n");
	}
}

function main() {
	console.log("\n== testIf()\n\n");
	testIf();

	console.log("\n== testSwitch()\n\n");
	console.log(testSwitch() + "\n");

	console.log("\n== testFor()\n\n");
	testFor();

	console.log("\n== testRange()\n\n");
	testRange();
}
