/* Generated by GoScript <github.com/kless/GoScript> */var test = {}; (function() {

const Pi = 3.14159265358979323846;
const pi2 = Pi;
const zero = 0.0;

const size = 1024;
const eof = -1;

const a = 3, b = 4, c = "foo";
const u = 0, v = 3;




const Sunday = 0;
const Monday = 1;
const Tuesday = 2;
const Wednesday = 3;
const Thursday = 4;
const Friday = 5;
const Partyday = 6;
const numberOfDays = 7;


const a0 = 0;
const a1 = 1;
const a2 = 2;


const b0 = 1 << 0;
const b1 = 1 << 1;
const b2 = 1 << 2;


const c0 = 0 * 42;
const c1 = 1 * 42;
const c2 = 2 * 42;


const x = 0;
const y = 0;


const bit0 = 1 << 0, mask0 = 1 << 0 - 1;
const bit1 = 1 << 1, mask1 = 1 << 1 - 1;

const bit3 = 1 << 3, mask3 = 1 << 3 - 1;


function main() {
	const F = 1;

	
	const Fa = 2;
	const fb = 3;

}

_export(test, [Pi, Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Partyday]);
})();
