/* Generated by GoJscript <github.com/kless/GoJscript> */var test = {}; (function() {

var A = "";
var a = 0;
var b = 0, c = 0, d = 0;
var e = 0;
var f = -1, g = -2;

var h = 0;
var i = 2.0, j = 3.0, k = "bar";


var l = true;
var m = 0;
var n = 3.0;
var o = "OMDB";






var a1 = new Array(32); for (var t=0; t<32; t++){ a1[t]=0; }
var a2 = new Array(2); for (var i0=0; i0<2; i0++){ a2[i0]=new Array(4); for (var t=0; t<4; t++){ a2[t]=0; }}

var a4 = new Array(1000); for (var t=0; t<1000; t++){ a4[t]=[0]; }
var a5 = new Array(4); for (var t=0; t<4; t++){ a5[t]=0; }
var a6 = new Array(3); for (var i0=0; i0<3; i0++){ a6[i0]=new Array(5); for (var t=0; t<5; t++){ a6[t]=0; }}
var a7 = new Array(2); for (var i0=0; i0<2; i0++){ a7[i0]=new Array(2); for (var i1=0; i1<2; i1++){ a7[i0][i1]=new Array(2); for (var t=0; t<2; t++){ a7[t]=0; }}}

var b1 = new Array(32); for (var t=0; t<32; t++){ b1[t]=0; }; b1 = [1, 2, 3, 4];
var b2 = new Array(4); for (var t=0; t<4; t++){ b2[t]=0; }; b2 = [1, , , 4];




var s1 = new Array(10);
var s2 = new Array(20);

var s3 = [2, 4, 6];
var s4 = [1, , 3];
var s5 = ["a", "b", "c"];




var m1 = {};
var m2 = {};
var m3 = {1: "first", 2: "second", 3: "third"};




var m4 = {1: "first", 2: 2, 3: 3};








var p0 = [0];
var p1 = [0];
var p2 = [false];


function main() {
	var Fa = 0, Fb = 10;
	var Fc = "c";
	
	var Fd = 20;
	var Fe = 0;

}

_export(test, [A]);
})();
