/* Generated by GoJscript <github.com/kless/GoJscript> */







function hello() { console.log("Hello world!"); }

function testSimpleFunc() {

	var max = function(a, b) {
		if (a > b) {
			return a;
		}
		return b;
	};

	var x = 3;
	var y = 4;
	var z = 5;

	var _ = max(x, y); max_xy = _[0];
	var _ = max(x, z); max_xz = _[0];

	alert("max(" + x + ", " + y + ") = " + max_xy + "\n");
	alert("max(" + x + ", " + z + ") = " + max_xz + "\n");
	alert("max(" + y + ", " + z + ") = " + max(y, z) + "\n");
}

function testResultVar() {


	var MySqrt = function(f) { var s = 0, ok = false;
		if (f > 0) {
			s = Math.sqrt(f), ok = true;
		}
		return [s, ok];
	};









}

function testByValue() {

	var add = function(v) {
		v = v + 1;
		return v;
	};

	var x = 3;
	alert("x =  " + x + "\n");

	var _ = add(x); x1 = _[0];
	alert("x+1 =  " + x1 + "\n");
	alert("x =  " + x + "\n");
}

function testByReference() {
	var add = function(v) {
		v[0] = v[0] + 1;
		return v[0];
	};

	var x = 3;
	alert("x =  " + x + "\n");

	var _ = add(x=[x]); x1 = _[0];
	alert("x+1 =  " + x1 + "\n");
	alert("x =  " + x + "\n");

	_ = add(x); x1 = _[0];
	alert("x+1 =  " + x1 + "\n");
	alert("x =  " + x + "\n");
}

function testByReference2() {
	var add = function(v, i) { v[0] += i; };

	var value = 6;
	var incr = 1;

	add(value=[value], incr);
	alert(value + "\n");

	add(value, incr);
	alert(value + "\n");
}

function testByReference3() {
	var x = 3;
	var y = x;

	y[0]++;
	console.log(x + "\n");

	y[0]++;
	console.log(x + "\n");
}

function testByReference4() {
	var x = 3;
	var f = function() {
		x = 4;
	};
	var y = x;

	f();
	console.log(y[0] + "\n");
}
