/* Generated by GoJscript <github.com/kless/GoScript> */

function min(x, y) {
	if (x < y) {
		return x;
	}
	return y;
}

function testIf() {
	var x = 3, y = 5;
	var max = 7;

	if (x > max) {
		x = max;
	}

	var z = 2; if (x < y) {
		return x;
	} else if (x > z) {
		return z;
	} else {
		return y;
	}
}

function testSwitch(tag) {

	var str = "";

	switch (tag) {
		default: return "zero";
		case 1: case 3: case 5: case 7: case 9: return "odd";
		case 2: case 4: case 6: case 8: return "even";
	}

	var x = tag; switch (1) {
		case x < 0:
			str = "negative"; break;
		default:
			str = "positive"; break;
	}






}
