/* Generated by GoScript <github.com/kless/GoScript> */



function declare_1() {


	var numbers;

	var code = "";
	if (numbers === undefined) {
		code = "OK";
	} else {
		code = "Error";
	}
	console.log("[" + code + "] value in declaration\n");


	numbers = {};

	if (numbers !== undefined) {
		code = "OK";
	} else {
		code = "Error";
	}
	console.log("[" + code + "] value using make\n");


	numbers["one"] = 1;
	numbers["ten"] = 10;
	numbers["trois"] = 3;


	if (numbers["trois"] === 3) {
		console.log("[OK] value of a key\n");
	} else {
		alert("[Error] Trois is the french word for the number: " + numbers["trois"] + "\n");
	}

}

function declare_2() {

	var rating2 = {"C": 5, "Go": 4.5, "Python": 4.5, "C++": 2};


	var rating = {};
	rating["C"] = 5;
	rating["Go"] = 4.5;
	rating["Python"] = 4.5;
	rating["C++"] = 2;


	var code = "";
	if (rating["Go"] === rating2["Go"]) {
		console.log("[OK] comparing same value\n");
	} else {
		alert("[Error] rating[\"Go\"]: " + rating["Go"] + "\trating2[\"Go\"]: " + rating2["Go"] + "\n");

	}


	rating["Go"] = 4.7;

	if (rating["Go"] !== rating2["Go"]) {
		code = "OK";
	} else {
		code = "Error";
	}
	console.log("[" + code + "] comparing different value\n");

}

function reference() {

	var m = {};
	m["Hello"] = "Bonjour";

	var m1 = m;
	m1["Hello"] = "Salut";


	if (m["Hello"] === m1["Hello"]) {
		console.log("[OK]\n");
	} else {
		alert("[Error] value in key: " + m["Hello"] + "\n");
	}

}

function main() {
	console.log("\n== declare_1\n");
	declare_1();
	console.log("\n== declare_2\n");
	declare_2();
	console.log("\n== reference\n");
	reference();
}
