/* Generated by GoScript <github.com/kless/GoScript> */



function valueNil() {
	var n;


	var msg = "declaration";
	if (n === undefined) {
		console.log("[OK] " + msg + "\n");
	} else {
		alert("[Error] " + msg + "\n");
	}


	n = {};


	msg = "using make";
	if (n !== undefined) {
		console.log("[OK] " + msg + "\n");
	} else {
		alert("[Error] " + msg + "\n");
	}

}

function declare_1() {


	var numbers;
	numbers = {};

	numbers["one"] = 1;
	numbers["ten"] = 10;
	numbers["trois"] = 3;


	if (numbers["trois"] === 3) {
		console.log("[OK]\n");
	} else {
		alert("[Error] Trois is the french word for the number: " + numbers["trois"] + "\n");
	}

}

function declare_2() {

	var rating2 = new g.M({"C": 5, "Go": 4.5, "Python": 4.5, "C++": 2}, 0);


	var rating = {};
	rating["C"] = 5;
	rating["Go"] = 4.5;
	rating["Python"] = 4.5;
	rating["C++"] = 2;


	var code = "";
	if (JSON.stringify(rating["Go"]) === JSON.stringify(rating2["Go"])) {
		console.log("[OK] comparing same value\n");
	} else {
		alert("[Error] rating[\"Go\"]: " + rating["Go"] + "\trating2[\"Go\"]: " + rating2["Go"] + "\n");

	}


	rating["Go"] = 4.7;

	if (JSON.stringify(rating["Go"]) !== JSON.stringify(rating2["Go"])) {
		code = "OK";
	} else {
		code = "Error";
	}
	console.log("[" + code + "] comparing different value\n");

}

function reference() {

	var m = {};
	m["Hello"] = "Bonjour";

	var m1 = m;
	m1["Hello"] = "Salut";


	if (JSON.stringify(m["Hello"]) === JSON.stringify(m1["Hello"])) {
		console.log("[OK]\n");
	} else {
		alert("[Error] value in key: " + m["Hello"] + "\n");
	}

}

function checkKey() {
	var rating = new g.M({"C": 5, "Go": 4.5, "Python": 4.5, "C++": 2}, 0);

	var csharp_rating = rating["C#"];

	if (csharp_rating === 0.00) {
		console.log("[OK]\n");
	} else {
		alert("[Error] value in key: " + csharp_rating + "\n");
	}


	var multMap = new g.M({1: {1: "one"}, 2: {2: "two"}}, "");

	var k_multMap = multMap[1][2];

	if (k_multMap === "") {
		console.log("[OK]\n");
	} else {
		alert("[Error] value in key: " + k_multMap + "\n");
	}

}

function main() {
	console.log("\n== valueNil\n");
	valueNil();
	console.log("\n== declare_1\n");
	declare_1();
	console.log("\n== declare_2\n");
	declare_2();
	console.log("\n== reference\n");
	reference();
	console.log("\n== checkKey\n");
	checkKey();
}
