/* Generated by GoScript <github.com/kless/GoScript> */



function Rectangle(width, height) {
	this.width=width; this.height=height;
}

Rectangle.prototype.area = function() {
	return this.width * this.height;
}

function Circle(radius) {
	this.radius=radius;
}

Circle.prototype.area = function() {
	return this.radius * this.radius * Math.PI;
}

function noMethod() {
	var area = function(r) {
		return r.width * r.height;
	};

	var r1 = new Rectangle(12, 2);
	var r2 = new Rectangle(9, 4);
	console.log("Area of r1 is: " + area(r1) + "\n");
	console.log("Area of r2 is: " + area(r2) + "\n");
}

function test_1() {
	var r1 = new Rectangle(12, 2);
	var r2 = new Rectangle(9, 4);
	var c1 = new Circle(10);
	var c2 = new Circle(25);


	console.log("Area of r1 is: " + r1.area() + "\n");
	console.log("Area of r2 is: " + r2.area() + "\n");
	console.log("Area of c1 is: " + c1.area() + "\n");
	console.log("Area of c2 is: " + c2.area() + "\n");
}

function main() {
	console.log("\n== noMethod()\n\n");
	noMethod();
	console.log("\n== test_1()\n\n");
	test_1();
}
