/* Generated by GoJscript <github.com/kless/GoJscript> */


var i = [0];
var hello = [""];
var p = [0];

(function() {
	p[0] = i;
	var helloPtr = hello;
}());

function declaration() {
	var i = [0];
	var hello = [""];
	var p = [0];

	p[0] = i;
	var helloPtr = hello;
}

function showAddress() {
	
var i = [9];
var hello = ["Hello world"];
var pi = [3.14];
var b = [true];


	console.log("Hexadecimal address of 'i' is: " + i + "\n");
	console.log("Hexadecimal address of 'hello' is: " + hello + "\n");
	console.log("Hexadecimal address of 'pi' is: " + pi + "\n");
	console.log("Hexadecimal address of 'b' is: " + b + "\n");
}

function access() {
	var hello = ["Hello, mina-san!"];

	var helloPtr = [""];
	helloPtr[0] = hello;

	var i = [6];
	var iPtr = i;

	console.log("The string \"hello\" is: " + hello + "\n");
	console.log("The string pointed to by \"helloPtr\" is: " + helloPtr[0] + "\n");
	console.log("The value of \"i\" is: " + i + "\n");
	console.log("The value pointed to by \"iPtr\" is: " + iPtr[0] + "\n");
}

function access_2() {
	var x = [3];
	var y = x;

	y[0]++;
	console.log("x is: " + x + "\n");

	y[0]++;
	console.log("x is: " + x + "\n");
}

function allocation() {
	var sum = 0;
	var doubleSum = [0];
	for (var i = 0; i < 10; i++) {
		sum += i;
	}

	doubleSum[0] = 0;
	doubleSum[0] = sum * 2;

	console.log("The sum of numbers from 0 to 10 is: " + sum + "\n");
	console.log("The double of this sum is: " + doubleSum[0] + "\n");
}

function main() {
	console.log("\n== showAddress()\n\n");
	showAddress();

	console.log("\n== access()\n\n");
	access();

	console.log("\n== access_2()\n\n");
	access_2();

	console.log("\n== allocation()\n\n");
	allocation();
}
