/* Generated by GoScript <github.com/kless/GoScript> */


var i = [0];
var hello = [""];
var p = [0];

(function() {
	p[0] = i;
	var helloPtr = hello;
	console.log("helloPtr: " + helloPtr + "\n");
}());

function declaration() {
	var i = [0];
	var hello = [""];
	var p = [0];

	p[0] = i;
	var helloPtr = hello;
	console.log("p:  " + p + " " + "\nhelloPtr: " + helloPtr + "\n");
}

function showAddress() {
	
	var i = [9];
	var hello = ["Hello world"];
	var pi = [3.14];
	var b = [true];


	console.log("Hexadecimal address of 'i' is: " + i + "\n");
	console.log("Hexadecimal address of 'hello' is: " + hello + "\n");
	console.log("Hexadecimal address of 'pi' is: " + pi + "\n");
	console.log("Hexadecimal address of 'b' is: " + b + "\n");
}

function access_1() {
	var hello = ["Hello, mina-san!"];

	var helloPtr = [""];
	helloPtr[0] = hello;

	var i = [6];
	var iPtr = i;

	console.log("The string \"hello\" is: " + hello + "\n");
	console.log("The string pointed to by \"helloPtr\" is: " + helloPtr[0] + "\n");
	console.log("The value of \"i\" is: " + i + "\n");
	console.log("The value pointed to by \"iPtr\" is: " + iPtr[0] + "\n");
}

function access_2() {
	var x = [3];
	var y = x;

	y[0]++;
	console.log("x is: " + x + "\n");

	y[0]++;
	console.log("x is: " + x + "\n");
}

function allocation() {
	var sum = 0;
	var doubleSum = [0];
	for (var i = 0; i < 10; i++) {
		sum += i;
	}

	doubleSum[0] = 0;
	doubleSum[0] = sum * 2;

	console.log("The sum of numbers from 0 to 10 is: " + sum + "\n");
	console.log("The double of this sum is: " + doubleSum[0] + "\n");
}

function parameterByValue() {

	var add = function(v) {
		v = v + 1;
		return v;
	};

	var x = 3;
	console.log("x = " + x + "\n");

	var x1 = add(x);
	console.log("x+1 = " + x1 + "\n");
	console.log("x = " + x + "\n");
}

function byReference_1() {
	var add = function(v) {
		v[0] = v[0] + 1;
		return v[0];
	};

	var x = [3];
	console.log("x = " + x + "\n");

	var x1 = add(x);
	console.log("x+1 = " + x1 + "\n");
	console.log("x = " + x + "\n");

	x1 = add(x);
	console.log("x+1 = " + x1 + "\n");
	console.log("x = " + x + "\n");
}

function byReference_2() {
	var add = function(v, i) { v[0] += i; };

	var value = [6];
	var incr = 1;

	add(value, incr);
	console.log(value + "\n");

	add(value, incr);
	console.log(value + "\n");
}

function byReference_3() {
	var x = [3];
	var f = function() {
		x[0] = 4;
	};
	var y = x;

	f();
	console.log(y[0] + "\n");
}

function main() {
	console.log("\n== declaration()\n\n");
	declaration();
	console.log("\n== showAddress()\n\n");
	showAddress();
	console.log("\n== access_1()\n\n");
	access_1();
	console.log("\n== access_2()\n\n");
	access_2();
	console.log("\n== allocation()\n\n");
	allocation();
	console.log("\n== parameterByValue()\n\n");
	parameterByValue();
	console.log("\n== byReference_1()\n\n");
	byReference_1();
	console.log("\n== byReference_2()\n\n");
	byReference_2();
	console.log("\n== byReference_3()\n\n");
	byReference_3();
}
