/* Generated by GoScript <github.com/kless/GoScript> */



function shortHand() {

	var array = []; for (var i=0; i<10; i++){ array[i]=0; } array = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'];

	var a_slice = [], b_slice = [];

	console.log("=== Slicing\n");
	a_slice = array.slice(4,8);console.log(a_slice + "\n");
	a_slice = array.slice(6,7);console.log(a_slice + "\n");

	console.log("\n=== Shorthands\n");
	a_slice = array.slice(0,3);console.log(a_slice + "\n");
	a_slice = array.slice(5);console.log(a_slice + "\n");
	a_slice = array.slice(0);console.log(a_slice + "\n");

	console.log("\n=== Slice of a slice\n");
	a_slice = array.slice(3,7);console.log(a_slice + "\n");
	b_slice = a_slice.slice(1,3);console.log(b_slice + "\n");
	b_slice = a_slice.slice(0,3);console.log(b_slice + "\n");
	b_slice = a_slice.slice(0);console.log(b_slice + "\n");
}

function main() {
	console.log("\n== shortHand()\n\n");
	shortHand();

}
