/* Generated by GoScript <github.com/kless/GoScript> */

var a;
var b, c, d;
var e = 0;
var f = -1, g = -2;

var h;
var i = 2.0, j = 3.0, k = "bar";


var l = true;
var m = 0;
var n = 3.0;
var o = "OMDB";






var a1 = new Array(32);
var a2 = new Array(2); for (var i0=0; i0<2; i0++){ a2[i0]=new Array(4); }

var a4 = new Array(1000);
var a5 = new Array(4);
var a6 = new Array(3); for (var i0=0; i0<3; i0++){ a6[i0]=new Array(5); }
var a7 = new Array(2); for (var i0=0; i0<2; i0++){ a7[i0]=new Array(2); for (var i1=0; i1<2; i1++){ a7[i0][i1]=new Array(2); }}

var b1 = new Array(4); b1 = [1,2,3,4];
var b2 = new Array(4); b2 = [1,,,4];




var s1 = new Array(10);
var s2 = new Array(20);

var s3 = [2,4,6];
var s4 = [1,,3];
var s5 = new Array(3); s5 = ["a","b","c"];




var m1 = {};
var m2 = {};
var m3 = {1:"first", 2:"second", 3:"third"};




var m4 = {1:"first", 2:2, 3:3};








var p0;
var p1 = 2;
var p2 = true;