// Copyright 2011  The "GoScript" Authors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

package goscript

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	//"io/ioutil"
	"os"
	//"path"
	//"strings"
)

// Represents the code transformed to JavaScript.
type transform struct {
	err      []error
	pointers []string

	text  map[int]string
	fset   *token.FileSet
}

func newTransform() *transform {
	return &transform{
		nil,
		make([]string, 0),
		make(map[int]string),
		token.NewFileSet(),
	}
}

// Returns the line number.
func (tr *transform) Line(expr ast.Spec) int {
	return tr.fset.Position(expr.Pos()).Line - 1
}

// * * *

// Compiles a Go source file into JavaScript.
// Writes the output in "filename" but with extension ".js".
func Compile(filename string) error {
	trans := newTransform()

	/* Parse several files
	parse.ParseFile(fset, "a.go", nil, 0)
	parse.ParseFile(fset, "b.go", nil, 0)
	*/

	// If Go sintaxis is incorrect then there will be an error.
	node, err := parser.ParseFile(trans.fset, filename, nil, 0) //parser.ParseComments)
	if err != nil {
		return err
	}

	for _, decl := range node.Decls {
		//fmt.Printf("%T : %v\n", decl,decl) //! TODO: to delete when it's finished

		switch decl.(type) {

		// http://golang.org/pkg/go/ast/#GenDecl || godoc go/ast GenDecl
		//  Tok    token.Token   // IMPORT, CONST, TYPE, VAR
		//  Specs  []Spec
		case *ast.GenDecl:
			genDecl := decl.(*ast.GenDecl)

			switch genDecl.Tok {
			case token.CONST:
				trans.getConst(genDecl.Specs)
			case token.TYPE:
				trans.getType(genDecl.Specs)
			case token.VAR:
				trans.getVar(genDecl.Specs)
			}
		}
	}

	if trans.err != nil {
		for _, err := range trans.err {
			fmt.Fprintf(os.Stderr, "%s\n", err.Error())
		}
		return errors.New("Error: not supported in JavaScript")
	}

	// === Write
	buf := new(bytes.Buffer)
	buf.WriteString("// Generated by GoScript <github.com/kless/GoScript>\n")

	for i, posLine, totalLines := 1, 0, len(trans.text);; i++ {
		if v, found := trans.text[i]; found {
			buf.WriteString(v)
			//fmt.Printf("%d: %s", i, v)
			posLine++
		} else {
			buf.WriteString("\n")
		}
		if posLine == totalLines {
			break
		}
	}
	fmt.Print(buf.String()) // TODO: delete*/

	//jsFile := strings.Replace(filename, path.Ext(filename), ".js", 1)
	//return ioutil.WriteFile(jsFile, buf.Bytes(), 0664)
	return nil
}
