/* Generated by GoScript <github.com/kless/GoScript> */















var g = {}; (function() {


function Export(pkg, exported) {
	var v; for (_ in exported) { v = exported[_];
		pkg.v = v;
	}
}







function M(m, z) {
	this.m=m;
	this.z=z;
}




M.prototype.get = function(k) {
	var v = this.m;


	for (var i = 0; i < arguments.length; i++) {
		v = v[arguments[i]];
	}

	if (v === undefined) {
		return this.z;
	}
	return v;
}



M.prototype.del = function(k) {
	this.m[k] = undefined;
}

g.Export(g, [Export, M]);
})();
