/* Generated by GoScript <github.com/kless/GoScript> */var test = {}; (function() {

var A = "";
var a = 0;
var b = 0, c = 0, d = 0;
var e = 0;
var f = -1, g = -2;

var h = 0;
var i = 2.0, j = 3.0, k = "bar";


var l = true;
var m = 0;
var n = 3.0;
var o = "OMDB";





var a1 = []; for (var i=0; i<32; i++){ a1[i]=0; }
var a2 = []; for (var i=0; i<2; i++){ a2[i]=[]; for (var j=0; j<4; j++){ a2[i][j]=0; }}

var a4 = []; for (var i=0; i<10; i++){ a4[i]={p:undefined}; }
var a5 = []; for (var i=0; i<4; i++){ a5[i]=0; }
var a6 = []; for (var i=0; i<3; i++){ a6[i]=[]; for (var j=0; j<5; j++){ a6[i][j]=0; }}
var a7 = []; for (var i=0; i<2; i++){ a7[i]=[]; for (var j=0; j<2; j++){ a7[i][j]=[]; for (var k=0; k<2; k++){ a7[i][j][k]=0; }}}

var b1 = []; for (var i=0; i<32; i++){ b1[i]=0; } b1 = [1, 2, 3, 4];
var b2 = []; for (var i=0; i<4; i++){ b2[i]=0; } b2 = [1, , , 4];




var s1 = g.MakeSlice(0, 10);
var s2 = g.MakeSlice(0, 10, 20);

var s3 = [2, 4, 6];
var s4 = [1, _, 3];
var s5 = ["a", "b", "c"];




var m1 = new g.M({}, 0);
var m2 = new g.M({}, 0);
var m3 = new g.M({
	1: "first",
	2: "second",
	3: "third"
}, "");
var m4 = new g.M({
	1: "first",
	2: 2,
	3: 3
}, undefined);




var p0 = {p:undefined};
var p1 = {p:undefined};
var p2 = {p:undefined};


function main() {
	var Fa = 0, Fb = 10;
	var Fc = "c";
	
	var Fd = 20;
	var Fe = 0;

}

g.Export(test, [A]);
})();
