/* Generated by GoScript <github.com/kless/GoScript> */






var x = 10;

(function() {
	x = 13;
}());

function testInit() {
	var code = "";
	if (x === 13) {
		code = "OK";
	} else {
		code = "Error";
	}
	console.log("[" + code + "]\n");
}

function singleLine() { console.log("[OK]\n"); }

function simpleFunc() {

	var max = function(a, b) {
		if (a > b) {
			return a;
		}
		return b;
	};

	var x = 3;
	var y = 4;
	var z = 5;

	var max_xy = max(x, y);

	if (max_xy === 4) {
		console.log("[OK] x,y\n");
	} else {
		alert("[Error] max(" + x + ", " + y + ") = " + max_xy + "\n");
	}


	var max_xz = max(x, z);

	if (max_xz === 5) {
		console.log("[OK] x,z\n");
	} else {
		alert("[Error] max(" + x + ", " + z + ") = " + max_xz + "\n");
	}



	if (max(y, z) === 5) {
		console.log("[OK] y,z\n");
	} else {
		alert("[Error] max(" + y + ", " + z + ") = " + max(y, z) + "\n");
	}

}

function twoOuputValues() {

	var SumAndProduct = function(A, B) {
		return [A + B, A * B];
	};

	var x = 3;
	var y = 4;
	var _ = SumAndProduct(x, y), xPLUSy = _[0], xTIMESy = _[1];


	if (xPLUSy === 7 && xTIMESy === 12) {
		console.log("[OK]\n");
	} else {
		alert("[Error] " + x + " + " + y + " = " + xPLUSy + "\t");
		alert("" + x + " * " + y + " = " + xTIMESy + "\n");
	}

}

function resultVariable() {


	var MySqrt = function(f) { var s = 0, ok = false;
		if (f > 0) {
			s = Math.sqrt(f), ok = true;
		}
		return [s, ok];
	};

	var results = new g.M({
		1: 1,
		2: 1.4142135623730951,
		3: 1.7320508075688772,
		4: 2,
		5: 2.23606797749979,
		6: 2.449489742783178,
		7: 2.6457513110645907,
		8: 2.8284271247461903,
		9: 3,
		10: 3.1622776601683795
	}, 0);

	var err = false;
	for (var i = -2.0; i <= 10; i++) {
		var _ = MySqrt(i), sqroot = _[0], ok = _[1];
		if (ok) {
			if (JSON.stringify(sqroot) !== JSON.stringify(results.get(i)[0])) {
				alert("[Error] The square root of " + i + " is " + sqroot + "\n");
				err = true;
			}
		} else {
			if (i !== -2.0 && i !== -1.0 && i !== 0) {
				alert("[Error] The square root for " + i + " should not be run\n");
				err = true;
			}
		}
	}
	if (!err) {
		console.log("[OK]\n");
	}
}

function testReturn() {
	var MySqrt = function(f) { var squareroot = 0, ok = false;
		if (f > 0) {
			squareroot = Math.sqrt(f), ok = true;
		}
		return [squareroot, ok];
	};

	var check = MySqrt(5)[1];


	var code = "";
	if (check) {
		code = "OK";
	} else {
		code = "Error";
	}
	console.log("[" + code + "]\n");

	var ok = MySqrt(0)[1]; if (!ok) {
		code = "OK";
	} else {
		code = "Error";
	}
	console.log("[" + code + "]\n");

}

function testPanic() {
	throw new Error("unreachable");
	throw new Error("not implemented: " + "foo" + "");
}

function main() {
	console.log("\n== testInit\n");
	testInit();
	console.log("\n== singleLine\n");
	singleLine();
	console.log("\n== simpleFunc\n");
	simpleFunc();
	console.log("\n== twoOuputValues\n");
	twoOuputValues();
	console.log("\n== resultVariable\n");
	resultVariable();
	console.log("\n== testReturn\n");
	testReturn();
	console.log("\n== testPanic\n");
	testPanic();
}
