/* Generated by GoScript <github.com/kless/GoScript> */



function valueNil() {
	var n;


	var msg = "declaration";
	if (n === undefined) {
		console.log("[OK] " + msg + "\n");
	} else {
		alert("[Error] " + msg + "\n");
	}


	n = new g.M({}, 0);


	msg = "using make";
	if (n !== undefined) {
		console.log("[OK] " + msg + "\n");
	} else {
		alert("[Error] " + msg + "\n");
	}

}

function declare_1() {


	var numbers;
	numbers = new g.M({}, 0);

	numbers.m["one"] = 1;
	numbers.m["ten"] = 10;
	numbers.m["trois"] = 3;


	if (numbers.get("trois") === 3) {
		console.log("[OK]\n");
	} else {
		alert("[Error] Trois is the french word for the number: " + numbers.get("trois") + "\n");
	}

}

function declare_2() {

	var rating2 = new g.M({"C": 5, "Go": 4.5, "Python": 4.5, "C++": 2}, 0);


	var rating = new g.M({}, 0);
	rating.m["C"] = 5;
	rating.m["Go"] = 4.5;
	rating.m["Python"] = 4.5;
	rating.m["C++"] = 2;


	var code = "";
	if (JSON.stringify(rating.get("Go")) === JSON.stringify(rating2.get("Go"))) {
		console.log("[OK] comparing same value\n");
	} else {
		alert("[Error] rating[\"Go\"]: " + rating.get("Go") + "\trating2[\"Go\"]: " + rating2.get("Go") + "\n");

	}


	rating.m["Go"] = 4.7;

	if (JSON.stringify(rating.get("Go")) !== JSON.stringify(rating2.get("Go"))) {
		code = "OK";
	} else {
		code = "Error";
	}
	console.log("[" + code + "] comparing different value\n");

}

function reference() {

	var m = new g.M({}, "");
	m.m["Hello"] = "Bonjour";

	var m1 = m;
	m1.m["Hello"] = "Salut";


	if (JSON.stringify(m.get("Hello")) === JSON.stringify(m1.get("Hello"))) {
		console.log("[OK]\n");
	} else {
		alert("[Error] value in key: " + m.get("Hello") + "\n");
	}

}

function checkKey() {
	var rating = new g.M({"C": 5, "Go": 4.5, "Python": 4.5, "C++": 2}, 0);
	var csharp_rating = rating.get("C#")[0];

	if (csharp_rating === 0.00) {
		console.log("[OK]\n");
	} else {
		alert("[Error] value in key: " + csharp_rating + "\n");
	}


	var multMap = new g.M({1: {1: "one"}, 2: {2: "two"}}, "");
	var k_multMap = multMap.get(1, 2)[0];

	if (k_multMap === "") {
		console.log("[OK]\n");
	} else {
		alert("[Error] value in multi-dimensional key: " + k_multMap + "\n");
	}


	var _ = rating.get("C#"), csharp_rating2 = _[0], ok = _[1];

	if (ok) {
		alert("[Error] using comma\n");
	} else {
		console.log("[OK] using comma\n");
	}
	if (csharp_rating2 === 0.00) {
		console.log("[OK] value (using comma)\n");
	} else {
		alert("[Error] value in key (using comma): " + csharp_rating2 + "\n");
	}

}

function main() {
	console.log("\n== valueNil\n");
	valueNil();
	console.log("\n== declare_1\n");
	declare_1();
	console.log("\n== declare_2\n");
	declare_2();
	console.log("\n== reference\n");
	reference();
	console.log("\n== checkKey\n");
	checkKey();
}
