/* Generated by GoScript <github.com/kless/GoScript> */



function valueNil() {
	var s = new g.S([], 0, 0);


	var msg = "value";
	if (s.isNil()) {
		console.log("[OK] " + msg + "\n");
	} else {
		alert("[Error] " + msg + "\n");
	}

	msg = "length";
	if (s.len === 0) {
		console.log("[OK] " + msg + "\n");
	} else {
		alert("[Error] " + msg + "\n");
	}

	msg = "capacity";
	if (s.cap === 0) {
		console.log("[OK] " + msg + "\n");
	} else {
		alert("[Error] " + msg + "\n");
	}

}

function shortHand() {

	var array = []; for (var i=0; i<10; i++){ array[i]=0; } array = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'];

	var a_slice = new g.S([], 0, 0), b_slice = new g.S([], 0, 0);

	var msg = "slicing";

	a_slice.set(array, 4, 8);

	if (a_slice.toString() === "efgh" && a_slice.len === 4 && a_slice.cap === 6) {
		console.log("[OK] " + msg + "\n");
	} else {
		alert("[Error] " + msg + "\n");
	}


	a_slice.set(array, 6, 7);

	if (a_slice.toString() === "g") {
		console.log("[OK]\n");
	} else {
		alert("[Error]\n");
	}


	msg = "shorthand";

	a_slice.set(array, 0, 3);

	if (a_slice.toString() === "abc" && a_slice.len === 3 && a_slice.cap === 10) {
		console.log("[OK] " + msg + "\n");
	} else {
		alert("[Error] " + msg + "\n");
	}


	a_slice.set(array, 5);

	if (a_slice.toString() === "fghij") {
		console.log("[OK]\n");
	} else {
		alert("[Error]\n");
	}


	a_slice.set(array, 0);

	if (a_slice.toString() === "abcdefghij") {
		console.log("[OK]\n");
	} else {
		alert("[Error]\n");
	}


	msg = "slice of a slice";

	a_slice.set(array, 3, 7);

	if (a_slice.toString() === "defg" && a_slice.len === 4 && a_slice.cap === 7) {
		console.log("[OK] " + msg + "\n");
	} else {
		alert("[Error] " + msg + "\n");
	}


	b_slice.set(a_slice, 1, 3);

	if (b_slice.toString() === "ef" && b_slice.len === 2 && b_slice.cap === 6) {
		console.log("[OK]\n");
	} else {
		alert("[Error]\n");
	}


	b_slice.set(a_slice, 0, 3);

	if (b_slice.toString() === "def") {
		console.log("[OK]\n");
	} else {
		alert("[Error]\n");
	}


	b_slice.set(a_slice, 0);

	if (b_slice.toString() === "defg") {
		console.log("[OK]\n");
	} else {
		alert("[Error]\n");
	}

}




function Max(slice) {
	var max = slice[0];
	for (var index = 1; index < slice.length; index++) {
		if (slice[index] > max) {
			max = slice[index];
		}
	}
	return max;
}

function useFunc() {

	var A1 = []; for (var i=0; i<10; i++){ A1[i]=0; } A1 = [1, 2, 3, 4, 5, 6, 7, 8, 9];
	var A2 = []; for (var i=0; i<4; i++){ A2[i]=0; } A2 = [1, 2, 3, 4];
	var A3 = []; for (var i=0; i<1; i++){ A3[i]=0; } A3 = [1];


	var slice = new g.S([], 0, 0);

	slice.set(A1, 0);

	if (Max(slice.f) === 9) {
		console.log("[OK] A1\n");
	} else {
		alert("[Error] A1\n");
	}


	slice.set(A2, 0);

	if (Max(slice.f) === 4) {
		console.log("[OK] A2\n");
	} else {
		alert("[Error] A2\n");
	}


	slice.set(A3, 0);

	if (Max(slice.f) === 1) {
		console.log("[OK] A3\n");
	} else {
		alert("[Error] A3\n");
	}

}



function PrintByteSlice(name, slice) {
	var s = "" + name + " is : [";
	for (var index = 0; index < slice.len - 1; index++) {
		s += "" + slice.f[index] + ",";
	}
	s += "" + slice.f[slice.len - 1] + "]";

	console.log(s + "\n");
}

function reference() {

	var A = []; for (var i=0; i<10; i++){ A[i]=0; } A = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'];


	var slice1 = g.NewSlice(A, 3, 7);
	var slice2 = g.NewSlice(A, 5);
	var slice3 = g.NewSlice(slice1, 0, 2);


	console.log("=== First content of A and the slices\n");
	PrintByteSlice("A", g.NewSlice(A, 0));
	PrintByteSlice("slice1", slice1);
	PrintByteSlice("slice2", slice2);
	PrintByteSlice("slice3", slice3);


	A[4] = 'E';
	console.log("\n=== Content of A and the slices, after changing 'e' to 'E' in array A\n");
	PrintByteSlice("A", g.NewSlice(A, 0));
	PrintByteSlice("slice1", slice1);
	PrintByteSlice("slice2", slice2);
	PrintByteSlice("slice3", slice3);


	slice2[1] = 'G';
	console.log("\n=== Content of A and the slices, after changing 'g' to 'G' in slice2\n");
	PrintByteSlice("A", g.NewSlice(A, 0));
	PrintByteSlice("slice1", slice1);
	PrintByteSlice("slice2", slice2);
	PrintByteSlice("slice3", slice3);
}



function resize() {
	var slice = new g.S([], 0, 0);


	slice = g.MakeSlice(0, 4, 5);

	if (slice.len === 4 && slice.cap === 5 && slice.f[0] === 0 && slice.f[1] === 0 && slice.f[2] === 0 && slice.f[3] === 0) {

		console.log("[OK] allocation\n");
	} else {
		alert("[Error] allocation\n");
	}



	slice.f[1] = 2, slice.f[3] = 3;

	if (slice.f[0] === 0 && slice.f[1] === 2 && slice.f[2] === 0 && slice.f[3] === 3) {
		console.log("[OK] change\n");
	} else {
		alert("[Error] change\n");
	}



	slice = g.MakeSlice(0, 2);

	if (slice.len === 2 && slice.cap === 2 && slice.f[0] === 0 && slice.f[1] === 0) {
		console.log("[OK] resize\n");
	} else {
		alert("[Error] resize\n");
	}

}



function main() {
	console.log("\n== valueNil\n");
	valueNil();
	console.log("\n== shortHand\n");
	shortHand();
	console.log("\n== useFunc\n");
	useFunc();
	console.log("\n== reference\n");
	reference();
	console.log("\n== resize\n");
	resize();
}
